# Generated by Django 3.0.5 on 2021-05-10 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('aboutPatient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='radio',
            name='idDocteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idDocteurRadio', to='users.Docteur'),
        ),
        migrations.AddField(
            model_name='radio',
            name='idPatient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idPatientRadio', to='users.Patient'),
        ),
        migrations.AddField(
            model_name='radio',
            name='idRadiologue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Radiologue'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='idDocteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idDocteurPrescription', to='users.Docteur'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='idPatient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idPatientPrescription', to='users.Patient'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='idChambre',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aboutPatient.Chambre'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='idDocteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idDocteurConsultation', to='users.Docteur'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='idDossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idDossierConsultation', to='aboutPatient.Dossier'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='idPrescription',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idPrescription', to='aboutPatient.Prescription'),
        ),
        migrations.AddField(
            model_name='chambre',
            name='idDocteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idDocteurChambre', to='users.Docteur'),
        ),
        migrations.AddField(
            model_name='chambre',
            name='idPatient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idPatientChambre', to='users.Patient'),
        ),
        migrations.AddField(
            model_name='analyse',
            name='idAnalyste',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Analyste'),
        ),
        migrations.AddField(
            model_name='analyse',
            name='idConsultation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aboutPatient.Consultation'),
        ),
        migrations.AddField(
            model_name='analyse',
            name='idDocteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idDocteurAnalyse', to='users.Docteur'),
        ),
        migrations.AddField(
            model_name='analyse',
            name='idPatient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idPatientAnalyse', to='users.Patient'),
        ),
    ]
